services:
  pgvector:
    image: 'pgvector/pgvector:pg16'
    environment:
      - 'POSTGRES_DB=postgres'
      - 'POSTGRES_PASSWORD=postgres'
      - 'POSTGRES_USER=@maniraj1'
    labels:
      - "org.springframework.boot.service-connection=postgres"
    ports:
      - '5433:5432'
